### ISSUE TITLE
NoRookies - Private Profiles

### ISSUE THREAD

**Issue by Rusty01** [GhoulofGSG9/ShineExtraPlugins#38]
Got a bit issue, trying to have a Veteran only server ( min 50+ hours ) But ANYONE with a public profile can play. Need an option to NOT allow people with public profiles to play

**Comment by GhoulofGSG9** [comment]
I may misunderstand this ticket but you really want to block all clients with a public profile? In case you don't want to take the steam playtime into account you can disable that via the config.

Otherwise if there are people able to join the server that shouldn't based on the no rookie limit please set Debug in the config to true and attach a log where on player is able to join a team who shouldn't.

**Comment by Rusty01** [comment]
Should it read the hive playtimes as well as the steam playtimes?
