### ISSUE TITLE
Is it possible for Epsilon Badges to not require Badges+?

### ISSUE THREAD

**Issue by keatsandyeats** [GhoulofGSG9/ShineExtraPlugins#39]
It was my understanding that the important methods from Badges+ were integrated into vanilla. I checked briefly and the ones used in Epsilon Badges all seem to be there. If the server disables Flag and Steam badges (activating only NSLTeams), then I would expect Epsilon Badges to not try to access badge files from Badges+. My reading of the code seems to support this. But this is not the case. All badges cease to display and each client gets [errors](https://gist.github.com/keatsandyeats/13d0f57c7ef47876c59bd154107f1357).

Is it possible for Epsilon Badges to not require Badges+? Or is the Badges+ code still used in a way I'm not seeing?

**Comment by GhoulofGSG9** [comment]
As you can see at https://github.com/GhoulofGSG9/BadgesPlus/blob/master/lua/entry/Badges%2B.entry BadgePlus does not load any code for ns2 build 313+ and is though no longer required to run the Epsilon Badge plugin unless you want to use badges that require files from the BadgesPlus badge pack (flags, steam trading card icons).

Your error indicates that the server and client have different amount of badge files mounted, which causes the gBadges enum to be out of sync.

**Comment by keatsandyeats** [comment]
Thanks for the response and for the tip about the error. Any idea about what could cause the server and client to have a different number of badges?

**Comment by GhoulofGSG9** [comment]
I know of two ways how that happens:
1. The server ops misunderstood how badges work and adds them directly to their server files instead of using a workshop mod
2. Due to https://trello.com/c/jfyZB37K/692-315-certain-assets-do-not-reload-after-file-mount this issue also occurs if a server ops mounts and unmounts a badge pack on the fly between rounds or if the client has played on another server with a different badge pack previously.
